apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "semantic-layer.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "semantic-layer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  SYSTEM_PROMPT: |
    {{ .Values.systemPrompt | indent 4 }}
  OLLAMA_MODEL: "{{ .Values.ollama.model }}"
  OLLAMA_URL: "http://ollama:11434/api/generate"
  APP_VERSION: "{{ .Values.image.tag }}"